### ISSUE TITLE
using SummernoteEditor causing java.lang.UnsupportedOperationException: remove

### ISSUE THREAD

**Issue by r1gm** [l0rdn1kk0n/wicket-bootstrap#1156]
Code : 
```java
        SummernoteConfig summernoteConfig = new SummernoteConfig();        
        summernoteConfig.withAirMode(false);        
        
        final SummernoteEditor summernoteEditor = new SummernoteEditor("summernote", new PropertyModel(docWiki, "content"), summernoteConfig);
        form.add(summernoteEditor);
```

Root cause:

java.lang.UnsupportedOperationException: remove
     at java.base/java.util.Iterator.remove(Iterator.java:102)
     at java.base/java.util.AbstractCollection.remove(AbstractCollection.java:285)
     at de.agilecoders.wicket.extensions.markup.html.bootstrap.editor.SummernoteEditor.renderHead(SummernoteEditor.java:107)
     at org.apache.wicket.Component.internalRenderHead(Component.java:2663)
     at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy$1.component(ChildFirstHeaderRenderStrategy.java:85)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:96)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:87)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:87)
     at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:51)
     at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy.renderChildHeaders(ChildFirstHeaderRenderStrategy.java:94)
     at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy.renderHeader(ChildFirstHeaderRenderStrategy.java:57)
     at org.apache.wicket.markup.html.internal.HtmlHeaderContainer.onComponentTagBody(HtmlHeaderContainer.java:171)
     at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2512)
     at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1586)
     at org.apache.wicket.Component.internalRender(Component.java:2317)
     at org.apache.wicket.Component.render(Component.java:2248)
     at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1447)
     at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1647)
     at org.apache.wicket.Page.onRender(Page.java:857)
     at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:126)
     at org.apache.wicket.Component.internalRender(Component.java:2317)
     at org.apache.wicket.Component.render(Component.java:2248)
     at org.apache.wicket.Page.renderPage(Page.java:997)
     at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
     at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
     at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:202)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:913)
     at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:63)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:294)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:255)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:277)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:208)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:307)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
     at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
     at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
     at java.base/java.lang.Thread.run(Thread.java:1583)

Complete stack:

org.apache.wicket.WicketRuntimeException: Exception in rendering component: [HtmlHeaderContainer [Component id = _header_]]
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2536)
     at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1586)
     at org.apache.wicket.Component.internalRender(Component.java:2317)
     at org.apache.wicket.Component.render(Component.java:2248)
     at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1447)
     at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1647)
     at org.apache.wicket.Page.onRender(Page.java:857)
     at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:126)
     at org.apache.wicket.Component.internalRender(Component.java:2317)
     at org.apache.wicket.Component.render(Component.java:2248)
     at org.apache.wicket.Page.renderPage(Page.java:997)
     at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
     at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
     at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:202)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:913)
     at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:63)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:294)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:255)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:277)

exception pointing to : 
```java
            // Remove picture button if no storage id is provided
            if (config.getStorageId() == null) {
            config.getButtons("Insert").remove("picture");    // <---
            }
```
     
     
Using :
- Wicket-bootstrap 7.0.8
- Wicket 10.2.0
- Oracle JDK 21

Best Regards,
Erwan

**Comment by r1gm** [comment]
found the problematic code : 

SummernoteConfig.java

```java
    private Map<String, List<String>> toolbarOptions = new LinkedHashMap<>() {
        private static final long serialVersionUID = 1L;

        {
            put("Style", Arrays.asList("style", "fontname", "fontsize", "color", "bold", "italic", "underline", "strikethrough", "clear"));
            put("Layout", Arrays.asList("ul", "ol", "paragraph", "height"));
            put("Insert", Arrays.asList("picture", "link", "video", "table", "hr"));
            put("Misc", Arrays.asList("fullscreen", "codeview", "undo", "redo", "help"));
        }
    };
```

the good old code : 

SummernoteConfig.java

```java
    private Map<String, List<String>> toolbarOptions = new LinkedHashMap<String, List<String>>() {
        {
            put("Style", Lists.newArrayList("style", "fontname", "fontsize", "color", "bold", "italic", "underline", "strikethrough", "clear"));
            put("Layout", Lists.newArrayList("ul", "ol", "paragraph", "height"));
            put("Insert", Lists.newArrayList("picture", "link", "video", "table", "hr"));
            put("Misc", Lists.newArrayList("fullscreen", "codeview", "undo", "redo", "help"));
        }
    };
```
