### ISSUE TITLE
wicket-bootstrap-sass can't use @use to import variable definitions

### ISSUE THREAD

**Issue by losmurfs** [l0rdn1kk0n/wicket-bootstrap#1161]
I have a file called siteSpecific.scss, one of the lines in siteSpecific.scss is:
$primary: #B30000;

When I try to use $primary in scss files that have @use 'siteSpecific.scss'; I get "message": "Undefined variable: \"$primary\".",

**Comment by martin-g** [comment]
Reproducer ?

**Comment by losmurfs** [comment]
Contents of globalImports.scss:
`$primary: #c00;`

Contents of styles.scss:
```
@use 'globalImports.scss';
div {
  color: $primary;
}
```

Snippet from HomePage.java:
```
...
public static final SassResourceReference CSS_REF =
    new SassResourceReference(HomePage.class, "styles.scss");
...
@Override
public void renderHead(IHeaderResponse response)
{
...
  response.render(CssHeaderItem.forReference(CSS_REF));
...
}
...
```
WebApp.java
```
...
public class WebApp extends WebApplication
{
  ...
   @Override
  protected void init()
  {
    ...
    SimpleSassCompilerOptionsFactory sassOptions = new SimpleSassCompilerOptionsFactory()
    {
      @Override
      public Options newOptions()
      {
        Options sassOptions = super.newOptions();
        sassOptions.getFunctionProviders().addAll(getSassFunctionProviders());
        return sassOptions;
      }
    };
    BootstrapSass.install(this,sassOptions);
    WicketWebjars.install(this,new WebjarsSettings());
    ...
  }
  ...
}
```
Error message:
09:05:25,507 WARN  [RequestCycleExtra] (default task-3) Handling the following exception: org.apache.wicket.WicketRuntimeException: An error occurred while compiling SASS resource vfs:/c:/wbm.ear/com/westring/web/styles.scss. {
  "status": 1,
  "file": "stdin",
  "line": 3,
  "column": 9,
  "message": "Undefined variable: \"$primary\".",
  "formatted": "Error: Undefined variable: \"$primary\".\n        on line 3:9 of stdin\n>>   background-color: $primary;\n\n   --------------------^\n"
}
	at deployment.wbm.ear//de.agilecoders.wicket.sass.SassCacheManager.getCss(SassCacheManager.java:166)
	at deployment.wbm.ear//de.agilecoders.wicket.sass.SassResourceStream.getString(SassResourceStream.java:57)
	at deployment.wbm.ear//org.apache.wicket.util.resource.AbstractStringResourceStream.getInputStream(AbstractStringResourceStream.java:171)
	at deployment.wbm.ear//org.apache.wicket.request.resource.PackageResource.newResourceResponse(PackageResource.java:357)
	at deployment.wbm.ear//org.apache.wicket.request.resource.AbstractResource.respond(AbstractResource.java:631)
	at deployment.wbm.ear//org.apache.wicket.request.handler.resource.ResourceRequestHandler.respond(ResourceRequestHandler.java:105)
	at deployment.wbm.ear//org.apache.wicket.request.handler.resource.ResourceReferenceRequestHandler.respond(ResourceReferenceRequestHandler.java:100)
	at deployment.wbm.ear//org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:910)
	at deployment.wbm.ear//org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:63)
	at deployment.wbm.ear//org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:294)
	at deployment.wbm.ear//org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:255)
	at deployment.wbm.ear//org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:277)
	at deployment.wbm.ear//org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:208)
	at deployment.wbm.ear//org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:307)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.wbm.ear//com.westring.web.controller.WebAppFilter.processRequest(WebAppFilter.java:446)
	at deployment.wbm.ear//com.westring.web.controller.MobileWebAppFilter.processRequest(MobileWebAppFilter.java:109)
	at deployment.wbm.ear//com.westring.web.controller.WebAppFilter.doFilter(WebAppFilter.java:269)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.security.elytron-web.undertow-server@4.1.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
	at org.wildfly.security.elytron-base@2.4.2.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
	at org.wildfly.security.elytron-base@2.4.2.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
	at org.wildfly.security.elytron-base@2.4.2.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
	at org.wildfly.security.elytron-web.undertow-server@4.1.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.3.13.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.3.13.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.3.13.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at org.wildfly.security.elytron-web.undertow-server-servlet@4.1.0.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
	at io.undertow.core@2.3.13.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@32.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:44)
	at io.undertow.core@2.3.13.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@32.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:51)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.3.13.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@32.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1421)
	at org.wildfly.extension.undertow@32.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1421)
	at org.wildfly.extension.undertow@32.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1421)
	at org.wildfly.extension.undertow@32.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1421)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256)
	at io.undertow.servlet@2.3.13.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101)
	at io.undertow.core@2.3.13.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.core@2.3.13.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at org.jboss.xnio@3.8.15.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.bit3.jsass.CompilationException: Error: Undefined variable: "$primary".
        on line 3:9 of stdin
>>   background-color: $primary;

**Comment by losmurfs** [comment]
Got it to work, instead of @use 'globalImports.scss'; I had to use @import 'classpath!/com/westring/web/globalImports.scss';
