### ISSUE TITLE
Add badge to NavbarButton

### ISSUE THREAD

**Issue by DanielaL** [l0rdn1kk0n/wicket-bootstrap#494]
Hi,
I am trying to have a component like a news/mail button in a navbar that shows a badge with the number of the newest incoming information and when the user clicks on it he gets a page with the news:
```
 private Component newsButton() {
	    	NavbarButton<Void> button = new NavbarButton<Void>(SearchNewsPage.class, GlyphIconType.envelope){
	    		@Override
		        public boolean isActive(Component item) {
					return getActiveMenu().equals(MenuItemEnum.NEWS);
		        }
	    	};
	    	button.add(new BadgeBehavior());
	    	return button;
	}
```
But when I try to add the BadgeBehavior like above I get a MarkupException:
```
org.apache.wicket.markup.MarkupException: /de/agilecoders/wicket/core/markup/html/bootstrap/navbar/Navbar.html: Component [component] (path = [1:navBar:navLeftList:5:component]) must be applied to a tag of type [span], not:  <a wicket:id= ''component '' href="./wicket/bookmarkable/com.maniola.appointmycompany.web.pages.SearchNewsPage">
```
How do I add a badge to a NavbarButton?
Best regards and many thanks in advance
Daniela

**Comment by martin-g** [comment]
Please provide few lines from the stacktrace so I can see where exactly it is being thrown.

**Comment by DanielaL** [comment]
Hi Martin,
thanks for your quick response. Here is the stacktrace:
```
at de.agilecoders.wicket.core.util.Components.createMarkupException(Components.java:97) ~[wicket-bootstrap-core-0.9.7.jar:0.9.7]
	at de.agilecoders.wicket.core.util.Components.assertTag(Components.java:81) ~[wicket-bootstrap-core-0.9.7.jar:0.9.7]
	at de.agilecoders.wicket.core.util.Components.assertTag(Components.java:66) ~[wicket-bootstrap-core-0.9.7.jar:0.9.7]
	at de.agilecoders.wicket.core.markup.html.bootstrap.block.BadgeBehavior.onComponentTag(BadgeBehavior.java:21) ~[wicket-bootstrap-core-0.9.7.jar:0.9.7]
	at org.apache.wicket.Component.renderComponentTag(Component.java:3970) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2540) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1493) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRender(Component.java:2379) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.render(Component.java:2307) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1390) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1554) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1529) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1484) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2549) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1493) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRender(Component.java:2379) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.render(Component.java:2307) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.list.ListView.renderItem(ListView.java:585) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.list.ListView.renderChild(ListView.java:574) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.repeater.AbstractRepeater.onRender(AbstractRepeater.java:94) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRender(Component.java:2379) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.render(Component.java:2307) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1390) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1554) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1529) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1484) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2549) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1493) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRender(Component.java:2379) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.render(Component.java:2307) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1390) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1554) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1529) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1484) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2549) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1493) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRender(Component.java:2379) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.render(Component.java:2307) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1390) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1554) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1529) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1484) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2549) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1493) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRender(Component.java:2379) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.render(Component.java:2307) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1390) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1554) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1529) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:689) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:76) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2549) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1493) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRender(Component.java:2379) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.render(Component.java:2307) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1390) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1554) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Page.onRender(Page.java:876) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:142) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.internalRender(Component.java:2379) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Component.render(Component.java:2307) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.Page.renderPage(Page.java:1010) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:121) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:274) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:165) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:861) ~[wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64) ~[wicket-request-6.12.0.jar:6.12.0]
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261) [wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218) [wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289) [wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259) [wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201) [wicket-core-6.12.0.jar:6.12.0]
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282) [wicket-core-6.12.0.jar:6.12.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.37]
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:149) [spring-orm-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.37]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.37]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.37]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.37]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.37]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.37]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.37]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) [catalina.jar:7.0.37]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.37]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.37]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.37]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.37]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852) [tomcat-coyote.jar:7.0.37]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_15]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_15]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_15]
```

**Comment by martin-g** [comment]
You are using `new NavbarButton<Void>(SearchNewsPage.class, GlyphIconType.envelope)`, i.e. just an icon as a label for the button.
Try with: 
```java
final IModel<String> label = Model.of("");
button = new NavbarButton<Void>(SearchNewsPage.class, label) {
  @Override protected Component newLabel(final String markupId) {
        return new Label(markupId, label).add(new BadgeBehavior());
    }
};
button.setIconType(GlyphIconType.envelope);
```

**Comment by DanielaL** [comment]
Hi Martin,
that works great, thanks :-)
Have a nice weekend.
Best regards 
Daniela
