### ISSUE TITLE
NullPointerException with BootsrapCheckbox in a FormGroup after upgrading from 0.9.6 to 0.9.10

### ISSUE THREAD

**Issue by tahitiangabriel** [l0rdn1kk0n/wicket-bootstrap#516]
Hi,

Scenario : I have a BootsrapCheckbox inside a FormGroup.
Since I've upgraded from wicket-bootstrap 0.9.6 to 0.9.10 I'm getting a NullPointerException :

```
java.lang.NullPointerException
     at de.agilecoders.wicket.core.markup.html.bootstrap.form.BootstrapCheckbox.getLabel(BootstrapCheckbox.java:123)
     at de.agilecoders.wicket.core.markup.html.bootstrap.form.FormGroup.onInitialize(FormGroup.java:185)
     at org.apache.wicket.Component.fireInitialize(Component.java:877)
     at org.apache.wicket.MarkupContainer$3.component(MarkupContainer.java:967)
     at org.apache.wicket.MarkupContainer$3.component(MarkupContainer.java:963)
     at org.apache.wicket.util.visit.Visits.visitChildren(Visits.java:144)
     at org.apache.wicket.util.visit.Visits.visitChildren(Visits.java:162)
     at org.apache.wicket.util.visit.Visits.visitChildren(Visits.java:123)
     at org.apache.wicket.util.visit.Visits.visitChildren(Visits.java:192)
     at org.apache.wicket.MarkupContainer.visitChildren(MarkupContainer.java:875)
     at org.apache.wicket.MarkupContainer.internalInitialize(MarkupContainer.java:962)
     at org.apache.wicket.Page.internalPrepareForRender(Page.java:238)
     at org.apache.wicket.Component.render(Component.java:2290)
     at org.apache.wicket.Page.renderPage(Page.java:1024)
```

The problem is related to this commit : https://github.com/l0rdn1kk0n/wicket-bootstrap/commit/5ba7458ac0be4c65dfc38d4f28b8bb6861b97fd6

```
    public BootstrapCheckbox setLabel(IModel<String> label) {
        checkbox.setLabel(label);
        return this;
    }
    @Override
    public IModel<String> getLabel() {
        return checkbox.getLabel();
    }
```
Shouldn't we use labelModel instead as checkbox?

Regards,

**Comment by martin-g** [comment]
> Shouldn't we use labelModel instead as checkbox?

I don't follow you. What exactly do you mean?

**Comment by tahitiangabriel** [comment]
In the BootsrapCheckbox there is a "labelModel" variable that store the label in the constructor.
So I think we should use the "labelModel" that is not null instead of the "checkbox" variable that is initialized in the "onInitialize" function.
Otherwise I get a NullPointerException in the FormGroup class.

**Comment by martin-g** [comment]
No. Those are different labels ...
The one that fails comes from `org.apache.wicket.markup.html.form.ILabelProvider#getLabel()`. It is used in i18n messages as `${label}`.
I'll see how to improve that.

**Comment by martin-g** [comment]
Could you please test with the latest -SNAPSHOT?

**Comment by tahitiangabriel** [comment]
@martin-g this does solve this problem, but now I'm having another problem.
As you have changed the BootstrapCheckbox from a GenericPanel<Boolean> to a FormComponentPanel<Boolean>, when the form is submitted, it tries to set the string "true" or "false" instead of Boolean.true and Boolean.false. I'm getting a "java.lang.IllegalArgumentException argument type mismatch".
So I think that BootstrapCheckbox need a specific converter like in the Checkbox component.

**Comment by martin-g** [comment]
Done.
Thanks for the feedback!

**Comment by tahitiangabriel** [comment]
Thank you so very much. It's working great now!

**Comment by martin-g** [comment]
:+1:
