### ISSUE TITLE
bootstrap.js wont load if located within a jar inside a jar

### ISSUE THREAD

**Issue by stalet** [l0rdn1kk0n/wicket-bootstrap#556]
I'm deploying a wicket-bootstrap application with spring boot. And i noticed while running `mvn spring-boot:run` all my resources loads ok, but when i deployed the application as a jar it will not load the bootstrap.js file.

This warning occurs in the log.
```
org.apache.wicket.request.resource.ResourceReferenceRegistry : A ResourceReference wont be created for a resource with key [scope: de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference; name: webjars/bootstrap/null/js/bootstrap.js; locale: null; style: null; variation: null] because it cannot be located.
```
And the url to the bootstrap.js inside my header tag is resolved to `<script type="text/javascript" id="bootstrap-js" defer="defer" src="./wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/bootstrap/null/js/bootstrap.js"></script>`.

The spring-boot jar artifact contains the org.webjars:bootstrap:3.3.5 artifact as a jar file inside the jar file. And the resource loader does not seem to cope with that.

I resolved the issue temporarily by exploding the bootstrap artifact by using a maven plugin like this:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>org.webjars</groupId>
                                    <artifactId>bootstrap</artifactId>
                                    <version>3.3.5</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <outputDirectory>${project.build.directory}/classes</outputDirectory>
                                    <includes>META-INF/resources/**/*.*</includes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
After that the application loads the resources without problems. But it seems unnecessary.

**Comment by martin-g** [comment]
Which version of wicket-webjars do you use?

**Comment by martin-g** [comment]
There is an improvement with https://github.com/l0rdn1kk0n/wicket-webjars/commit/5846dcd0d4c10019f6544b50f5f2f5ca40774c61, part of 0.4.8

**Comment by stalet** [comment]
I'm using webjars 0.5.2

**Comment by martin-g** [comment]
Please upgrade to 0.5.3.

**Comment by stalet** [comment]
Same result:

2015-09-29 14:04:34.105  WARN 23238 --- [nio-7777-exec-1] o.a.w.r.r.ResourceReferenceRegistry      : A ResourceReference wont be created for a resource with key [scope: de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference; name: webjars/bootstrap/null/js/bootstrap.js; locale: null; style: null; variation: null] because it cannot be located.

**Comment by martin-g** [comment]
Can you set a breakpoint at https://github.com/l0rdn1kk0n/wicket-webjars/commit/5846dcd0d4c10019f6544b50f5f2f5ca40774c61#diff-73faf5abe3cbf9169baaf39e1c400b31R49 and see what happens ?

Otherwise please create a quickstart app, put it in your GitHub and I'll take a look later.
Thanks!

**Comment by stalet** [comment]
isWarFile is false, since the outer artifact is indeed a jar too. I am packagin my spring-boot application as a jar (not war). I'll try to package it as a war to see if that is a workaround.

**Comment by stalet** [comment]
Changing the artifact to war changed the code to run, the XxxApplication line is Bootstrap.install(this, settings);

2015-09-29 14:45:54.659 ERROR 24601 --- [ost-startStop-1] o.a.wicket.protocol.http.WicketFilter    : The initialization of an application with name 'wicket-filter' has failed.

java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at de.agilecoders.wicket.webjars.collectors.JarAssetPathCollector.newJarFile(JarAssetPathCollector.java:78)
	at de.agilecoders.wicket.webjars.collectors.JarAssetPathCollector.collect(JarAssetPathCollector.java:39)
	at de.agilecoders.wicket.webjars.collectors.AssetsMap.getAssetPaths(AssetsMap.java:137)
	at de.agilecoders.wicket.webjars.collectors.AssetsMap.createFullPathIndex(AssetsMap.java:156)
	at de.agilecoders.wicket.webjars.collectors.AssetsMap.<init>(AssetsMap.java:46)
	at de.agilecoders.wicket.webjars.util.WebJarAssetLocator.<init>(WebJarAssetLocator.java:28)
	at de.agilecoders.wicket.webjars.util.file.WebjarsResourceFinder.newFullPathProvider(WebjarsResourceFinder.java:46)
	at de.agilecoders.wicket.webjars.util.file.WebjarsResourceFinder.<init>(WebjarsResourceFinder.java:34)
	at de.agilecoders.wicket.webjars.WicketWebjars.install(WicketWebjars.java:75)
	at de.agilecoders.wicket.webjars.WicketWebjars.install(WicketWebjars.java:51)
	at de.agilecoders.wicket.core.Bootstrap.install(Bootstrap.java:88)
	at xx.xx.XxxApplication.init(XxxApplication.java:60)
	at org.apache.wicket.Application.initApplication(Application.java:919)
	at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:429)
	at org.apache.wicket.protocol.http.WicketFilter.init(WicketFilter.java:353)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4574)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5193)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by stalet** [comment]
The application still works when running `mvn spring-boot:run`
If you'd like i can make a small project to show the error.

**Comment by martin-g** [comment]
Yes, please.
I don't use Spring Boot myself so please give me also the steps to reproduce, i.e. the steps to build and run.
Thanks!

**Comment by stalet** [comment]
Here you go: https://github.com/stalet/wicket7-bootstrap-starter

When starting the application with `mvn spring-boot:run` it works fine.
if building with `mvn clean install` and run with `java -jar target/wicket7-bootstrap-starter.jar` it fails.

There is also the fix i mentioned in there. You can enable that with `mvn clean install -Pfix-jar` and then the `java -jar target/wicket7-bootstrap-starter.jar` works again.

Enjoy! And let me know if there is anything more you need from me.

**Comment by martin-g** [comment]
See https://github.com/l0rdn1kk0n/wicket-webjars/issues/37.
I've pushed a fix, but it seems now the startup time increased twice!
I have to find a way how to filter non-webjars jar and do not scan them.

**Comment by stalet** [comment]
I tested it, it adds a 10-15 second delay in the boot process, but it works...

**Comment by martin-g** [comment]
The delay depends on the number and size of the jar files in the classpath.
I'll take a deeper look again in the coming days.

**Comment by MarcGiffing** [comment]
I think the cause of the performance problem is that you scan folders in all jar files. As I understand the resources are located in the META-INF folder. Did we have to scan all packages?

I've changed the resourcePattern to 
`this.resourcePattern = Pattern.compile("META-INF/*/.*");`

and added a breaking condition to handle to skip other folders.

Is it right that the resources are located in the META-INF folder?

**Comment by martin-g** [comment]
I have to double check but I think it is `/META-INF/webjars/**`
