### ISSUE TITLE
DropZoneFileUpload throws UnsupportedOperationException: Called operation not supported for TokenBuffer

### ISSUE THREAD

**Issue by SigitAri** [l0rdn1kk0n/wicket-bootstrap#560]
```
org.apache.wicket.WicketRuntimeException: Exception in rendering component: [HtmlHeaderContainer [Component id = _header_]]
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2588)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1543)
	at org.apache.wicket.Component.internalRender(Component.java:2379)
	at org.apache.wicket.Component.render(Component.java:2307)
	at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1407)
	at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1604)
	at org.apache.wicket.Page.onRender(Page.java:879)
	at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:143)
	at org.apache.wicket.Component.internalRender(Component.java:2379)
	at org.apache.wicket.Component.render(Component.java:2307)
	at org.apache.wicket.Page.renderPage(Page.java:1018)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:865)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: de.agilecoders.wicket.jquery.util.Json$ParseException: java.lang.IllegalArgumentException: Called operation not supported for TokenBuffer (through reference chain: java.util.LinkedHashMap["previewTemplate"])
	at de.agilecoders.wicket.jquery.util.Json.toJson(Json.java:75)
	at de.agilecoders.wicket.jquery.util.Json.stringify(Json.java:140)
	at de.agilecoders.wicket.jquery.AbstractConfig.toJsonString(AbstractConfig.java:35)
	at de.agilecoders.wicket.extensions.markup.html.bootstrap.fileUpload.DropZoneFileUpload.renderHead(DropZoneFileUpload.java:116)
	at org.apache.wicket.Component.renderHead(Component.java:4478)
	at org.apache.wicket.Component.internalRenderHead(Component.java:2714)
	at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy$1.component(ChildFirstHeaderRenderStrategy.java:85)
	at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:96)
	at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:87)
	at org.apache.wicket.markup.renderStrategy.DeepChildFirstVisitor.visit(DeepChildFirstVisitor.java:51)
	at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy.renderChildHeaders(ChildFirstHeaderRenderStrategy.java:78)
	at org.apache.wicket.markup.renderStrategy.ChildFirstHeaderRenderStrategy.renderHeader(ChildFirstHeaderRenderStrategy.java:57)
	at org.apache.wicket.markup.html.internal.HtmlHeaderContainer.onComponentTagBody(HtmlHeaderContainer.java:171)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2564)
	... 46 common frames omitted
Caused by: java.lang.IllegalArgumentException: Called operation not supported for TokenBuffer (through reference chain: java.util.LinkedHashMap["previewTemplate"])
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2035)
	at de.agilecoders.wicket.jquery.util.Json.toJson(Json.java:73)
	... 60 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Called operation not supported for TokenBuffer (through reference chain: java.util.LinkedHashMap["previewTemplate"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:187)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:495)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:412)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:27)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1902)
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2030)
	... 61 common frames omitted
Caused by: java.lang.UnsupportedOperationException: Called operation not supported for TokenBuffer
	at com.fasterxml.jackson.databind.util.TokenBuffer._reportUnsupportedOperation(TokenBuffer.java:1066)
	at com.fasterxml.jackson.databind.util.TokenBuffer.writeRawValue(TokenBuffer.java:709)
	at de.agilecoders.wicket.jquery.util.serializer.RawSerializer.serialize(RawSerializer.java:18)
	at de.agilecoders.wicket.jquery.util.serializer.RawSerializer.serialize(RawSerializer.java:15)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:491)
	... 66 common frames omitted
```

Java:

```java
        final DropZoneFileUpload fileFld = new DropZoneFileUpload("fileFld") {
            @Override
            protected void onUpload(AjaxRequestTarget ajaxRequestTarget, Map<String, List<FileItem>> map) {
                final FileItem first = map.values().iterator().next().get(0);
                HistogramPage.this.histogram.loadInput(first.getContentType(), first.get());
                HistogramPage.this.histogram.run();
                ajaxRequestTarget.add(origImg, resultDiv);
                info("Loaded file " + first.getName() + " (" + first.getContentType() + ")");
            }
        };
        add(fileFld);
```

Markup:

```html
<p><input type="file" wicket:id="fileFld"/></p>
```

wicket-bootstrap 0.10.3, jackson 2.4.6, spring-boot 1.2.6, wicket 7.0.0

Maybe this is bug for https://github.com/l0rdn1kk0n/wicket-jquery-selectors ?
Related to https://github.com/FasterXML/jackson-databind/issues/348#issuecomment-86977000

Tag @ceefour

**Comment by martin-g** [comment]
Please try with Jackson 2.6.2.
If it still fails then please explain the steps to reproduce. I  don't see
such problem in the samples app.
Thanks!

**Comment by ceefour** [comment]
With Jackson 2.6.2 that problem is gone, then i got NullPointerException regarding DropZoneConfig. I'll post the stacktrace when I have it later

**Comment by martin-g** [comment]
I'll close this issue.
Please create a new one for the new problem.
Thanks!
