### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.wicket.Application.setMetaData(Lorg/apache/wicket/MetaDataKey;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by ashkankzme** [l0rdn1kk0n/wicket-bootstrap#564]
I'm using wicket 7.1.0 and my wicket-tests won't pass!
I'm also using Wicket-Bootstrap 0.9.7,
Here's the error I'm getting : 

java.lang.NoSuchMethodError: org.apache.wicket.Application.setMetaData(Lorg/apache/wicket/MetaDataKey;Ljava/lang/Object;)V
	at de.agilecoders.wicket.core.Bootstrap.install(Bootstrap.java:81)
	at de.agilecoders.wicket.core.Bootstrap.install(Bootstrap.java:110)
	at ir.ashkankazemi.resume.WicketApplication.init(WicketApplication.java:30)
	at org.apache.wicket.Application.initApplication(Application.java:950)
	at org.apache.wicket.util.tester.BaseWicketTester.<init>(BaseWicketTester.java:340)
	at org.apache.wicket.util.tester.BaseWicketTester.<init>(BaseWicketTester.java:266)
	at org.apache.wicket.util.tester.BaseWicketTester.<init>(BaseWicketTester.java:239)
	at org.apache.wicket.util.tester.WicketTester.<init>(WicketTester.java:203)
	at ir.ashkankazemi.resume.TestHomePage.setUp(TestHomePage.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)

I think the problem might be about the change of wicket version, maybe the signature of the function setMetadata changed but you guys are returning the old Application version? (like the issue here : https://github.com/decebals/wicket-dashboard/issues/16#issuecomment-52776409 )

**Comment by martin-g** [comment]
You have to use Wicket Bootstrap 0.10.x with Wicket 7.
This is mentioned at the top of the README.
