### ISSUE TITLE
Modal component fails with NullPointerException when using a header

### ISSUE THREAD

**Issue by heryqk** [l0rdn1kk0n/wicket-bootstrap#599]
When calling Modal.header(IModel model), I keep getting

```
java.lang.NullPointerException
     at de.agilecoders.wicket.core.markup.html.bootstrap.dialog.Modal.header(Modal.java:250)
     at wicket.bootstrap.HomePage.<init>(HomePage.java:92)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
     at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:171)
     at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:76)
```
If I comment the header out, I can use the modal without any issues.

See attached QuickStart to replicate.

[ModalQuickstart.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/245666/ModalQuickstart.zip)

**Comment by martin-g** [comment]
Thanks!

**Comment by tahitiangabriel** [comment]
@martin-g. I'm facing this issue.  Where can I find a snapshot? I don't see it in sonatype anymore...

**Comment by tahitiangabriel** [comment]
@martin-g Nevermind I deployed it on my own repo..

**Comment by martin-g** [comment]
Yes, Travis is not very reliable lately.
I've just uploaded new snapshots from 0.9 and 0.10 series.
I'll make a new release this week. First want to fix the newly opened issues.
