### ISSUE TITLE
BootstrapListView fails to render when styled

### ISSUE THREAD

**Issue by heryqk** [l0rdn1kk0n/wicket-bootstrap#612]
BootstrapListView fails to render when styled with:

`java.lang.NullPointerException
     at de.agilecoders.wicket.core.markup.html.bootstrap.list.BootstrapListView.unstyled(BootstrapListView.java:59)
     at wicket.bootstrap.HomePage.<init>(HomePage.java:36)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
     at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:171)
     at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:76)
     at org.apache.wicket.DefaultMapperContext.newPageInstance(DefaultMapperContext.java:133)`

Also, I'm unsure about the benefits of this class as the component would be attached to `<li>` and not `<ul>` markup.

[BootstrapListViewQuickstart.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/268883/BootstrapListViewQuickstart.zip)

**Comment by martin-g** [comment]
Thanks!
