### ISSUE TITLE
BootstrapSlider getInput() needs to be overridden

### ISSUE THREAD

**Issue by francois92** [l0rdn1kk0n/wicket-bootstrap#685]
Hi Martin,

When the FormComponent # validate() (on a BootstrapSlider) occurs
convertInput() is called and performs the following task :
converter.convertToObject(getInput(), getLocale());

getInput() return a String "X,Y" but BootstrapSlider#Bootstrap-XXXX-SliderConverter expect for "[X,Y]"
if the value is a XxxxxxRangeValue

getInput() should be overridden in BootstrapSlider.
DateTimeField does it.

Here is the stacktrace if getInput is not overridden

java.lang.NumberFormatException: For input string: "3,10"
     at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
     at java.lang.Integer.parseInt(Integer.java:580)
     at java.lang.Integer.parseInt(Integer.java:615)
     at de.agilecoders.wicket.extensions.slider.util.IntegerValue.fromString(IntegerValue.java:21)
     at de.agilecoders.wicket.extensions.slider.BootstrapSlider$BootstrapIntegerSliderConverter.convertToObject(BootstrapSlider.java:88)
     at de.agilecoders.wicket.extensions.slider.BootstrapSlider$BootstrapIntegerSliderConverter.convertToObject(BootstrapSlider.java:81)
     at org.apache.wicket.markup.html.form.FormComponent.convertInput(FormComponent.java:1183)
     at org.apache.wicket.markup.html.form.AbstractTextComponent.convertInput(AbstractTextComponent.java:129)
     

 
[quickstart-slider.zip](https://github.com/l0rdn1kk0n/wicket-bootstrap/files/1075340/quickstart-slider.zip)

<wicket.version>8.0.0-M6</wicket.version>
<wicket-bootstrap.version>2.0.0-M5</wicket-bootstrap.version>

     
François

**Comment by martin-g** [comment]
Thanks for the report, @francois92 !
