### ISSUE TITLE
Some sample pages are showing exceptions

### ISSUE THREAD

**Issue by chrisco484** [l0rdn1kk0n/wicket-bootstrap#709]
Some of the sample pages are showing exceptions with fasterxml listed in the stack trace.

For example:

http://coding.teliclab.info/wicket-7.x/javascript

**Comment by h0l0gram** [comment]
Looks very similar to https://github.com/l0rdn1kk0n/wicket-jquery-selectors/issues/11 and https://github.com/FasterXML/jackson-databind/issues/743


```
Root cause:

java.lang.UnsupportedOperationException: Called operation not supported for TokenBuffer
     at com.fasterxml.jackson.databind.util.TokenBuffer._reportUnsupportedOperation(TokenBuffer.java:1066)
     at com.fasterxml.jackson.databind.util.TokenBuffer.writeRawValue(TokenBuffer.java:709)
     at de.agilecoders.wicket.jquery.util.serializer.RawSerializer.serialize(RawSerializer.java:18)
     at de.agilecoders.wicket.jquery.util.serializer.RawSerializer.serialize(RawSerializer.java:15)
     at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:557)
     at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:466)
     at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:29)
     at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
     at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2242)
     at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2369)
     at de.agilecoders.wicket.jquery.util.Json.toJson(Json.java:73)
     at de.agilecoders.wicket.jquery.util.Json.stringify(Json.java:140)
     at de.agilecoders.wicket.jquery.AbstractConfig.toJsonString(AbstractConfig.java:35)
     at de.agilecoders.wicket.extensions.markup.html.bootstrap.form.typeaheadV10.Typeahead.getDomR
...
```

**Comment by martin-g** [comment]
Cannot reproduce the problem locally neither in `wicket-7.x` nor in `wicket-8.x` branch.
If you can reproduce it with locally running examples I'd be happy to debug.
The demo is hosted by a volunteer and I have no access to it.
