### ISSUE TITLE
SassResourceReference does not work if SCSS files are in JARs

### ISSUE THREAD

**Issue by reckart** [l0rdn1kk0n/wicket-bootstrap#852]
It appears that JSASS only knows how to compile SCSS files that are residing on the file system, but not if they are located in JARs.

```
Caused by: io.bit3.jsass.CompilationException: Internal Error: File to read not found or unreadable: jar:file:/home/user/.m2/repository/de/tudarmstadt/ukp/clarin/webanno/webanno-ui-core/4.0.0-SNAPSHOT/webanno-ui-core-4.0.0-SNAPSHOT.jar!/de/tudarmstadt/ukp/clarin/webanno/ui/core/css/theme/bootstrap.scss

	at io.bit3.jsass.adapter.NativeAdapter.compileFile(Native Method) ~[jsass-5.10.3.jar:5.10.3]
	at io.bit3.jsass.adapter.NativeAdapter.compile(NativeAdapter.java:44) ~[jsass-5.10.3.jar:5.10.3]
	at io.bit3.jsass.Compiler.compile(Compiler.java:127) ~[jsass-5.10.3.jar:5.10.3]
	at io.bit3.jsass.Compiler.compileFile(Compiler.java:79) ~[jsass-5.10.3.jar:5.10.3]
	at de.agilecoders.wicket.sass.SassCacheManager.getCss(SassCacheManager.java:133) ~[wicket-bootstrap-sass-3.0.0-M13.jar:?]
	... 92 more
```

**Comment by martin-g** [comment]
Fixed by merging your PR!
